language: csharp
os: linux
solution: reNX.sln
sudo: false

cache:
    directories:
        - ./reNX.Tests/bin/Release/data

script:
    - xbuild /t:Rebuild /p:Configuration=Release reNX.sln
#    - mono ./packages/NUnit.Runners.*/tools/nunit-console.exe ./reNX.Tests/bin/Release/reNX.Tests.dll

notifications:
    email: false
    irc:
        channels:
            - "irc.fyrechat.net#vana-commits"
        skip_join: true
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} - %{author}): %{message}"

